# Generated by Django 5.1.3 on 2024-11-06 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatEditoriales',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('editorial', models.CharField(max_length=255)),
                ('activo', models.CharField(max_length=1)),
            ],
            options={
                'verbose_name_plural': 'Editoriales',
                'db_table': 'cat_editoriales',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CatIdioma',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('idioma', models.CharField(max_length=255)),
                ('activo', models.CharField(max_length=1)),
            ],
            options={
                'verbose_name_plural': 'Idiomas',
                'db_table': 'cat_idioma',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ConfEstadoEntrega',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=255)),
                ('activo', models.CharField(max_length=1)),
            ],
            options={
                'verbose_name_plural': 'Estados de Entrega',
                'db_table': 'conf_estadoentrega',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ConfGenero',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('genero', models.CharField(max_length=255)),
                ('activo', models.CharField(max_length=1)),
            ],
            options={
                'verbose_name_plural': 'Géneros',
                'db_table': 'conf_genero',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ConfNacionalidad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nacionalidad', models.CharField(max_length=255)),
                ('siglas', models.CharField(max_length=5)),
                ('activo', models.CharField(max_length=1)),
            ],
            options={
                'verbose_name_plural': 'Nacionalidades',
                'db_table': 'conf_nacionalidad',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='LogTipoUsuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=255)),
                ('activo', models.CharField(max_length=1)),
            ],
            options={
                'verbose_name_plural': 'Tipos de Usuario',
                'db_table': 'log_tipousuario',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CatLibros',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('precio', models.FloatField()),
                ('descuento', models.FloatField()),
                ('iva', models.FloatField()),
                ('fechapublicacion', models.DateField()),
                ('portada', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('sinopsis', models.CharField(max_length=1000)),
                ('fecharegistro', models.DateField()),
                ('paginas', models.IntegerField()),
                ('activo', models.CharField(max_length=1)),
                ('ideditorial', models.ForeignKey(db_column='ideditorial', on_delete=django.db.models.deletion.RESTRICT, to='digital.cateditoriales')),
                ('ididioma', models.ForeignKey(db_column='ididioma', on_delete=django.db.models.deletion.RESTRICT, to='digital.catidioma')),
                ('idgenero', models.ForeignKey(db_column='idgenero', on_delete=django.db.models.deletion.RESTRICT, to='digital.confgenero')),
            ],
            options={
                'verbose_name_plural': 'Libros',
                'db_table': 'cat_libros',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ConfAutor',
            fields=[
                ('idautor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('apellidopaterno', models.CharField(max_length=255)),
                ('apellidomaterno', models.CharField(max_length=255)),
                ('fechanacimiento', models.DateField()),
                ('fecharegistro', models.DateField()),
                ('activo', models.CharField(default=None, max_length=1, null=True)),
                ('idnacionalidad', models.ForeignKey(db_column='idnacionalidad', on_delete=django.db.models.deletion.RESTRICT, to='digital.confnacionalidad')),
            ],
            options={
                'verbose_name_plural': 'Autores',
                'db_table': 'conf_autores',
            },
        ),
        migrations.CreateModel(
            name='InventarioLibro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('activo', models.CharField(max_length=1)),
                ('idlibro', models.ForeignKey(db_column='idlibro', on_delete=django.db.models.deletion.RESTRICT, to='digital.catlibros')),
            ],
            options={
                'verbose_name_plural': 'Inventarios de Libros',
                'db_table': 'inv_inventariolibros',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='LibroAutor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('idautor', models.ForeignKey(db_column='idautor', on_delete=django.db.models.deletion.RESTRICT, to='digital.confautor')),
                ('idlibro', models.ForeignKey(db_column='idlibro', on_delete=django.db.models.deletion.RESTRICT, to='digital.catlibros')),
            ],
            options={
                'verbose_name_plural': 'Relacion Libros Autores',
                'db_table': 'cat_librosautores',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='LogUsuarios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255)),
                ('contraseña', models.CharField(max_length=255)),
                ('nombre', models.CharField(max_length=255)),
                ('apellidopaterno', models.CharField(max_length=255)),
                ('apellidomaterno', models.CharField(max_length=255)),
                ('fecharegistro', models.DateField()),
                ('telefono', models.CharField(blank=True, default=None, max_length=15, null=True)),
                ('fechanacimiento', models.DateField(blank=True, default=None, null=True)),
                ('activo', models.CharField(max_length=1)),
                ('idtipousuario', models.ForeignKey(db_column='idtipousuario', on_delete=django.db.models.deletion.RESTRICT, to='digital.logtipousuario')),
            ],
            options={
                'verbose_name_plural': 'Usuarios',
                'db_table': 'log_usuarios',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CarroDeCompra',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('activo', models.CharField(max_length=1)),
                ('idlibro', models.ForeignKey(db_column='idlibro', on_delete=django.db.models.deletion.RESTRICT, to='digital.catlibros')),
                ('idusuario', models.ForeignKey(db_column='idusuario', on_delete=django.db.models.deletion.RESTRICT, to='digital.logusuarios')),
            ],
            options={
                'verbose_name_plural': 'Carro de compra',
                'db_table': 'ven_carrodecompra',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('importe', models.FloatField()),
                ('descuento', models.FloatField()),
                ('iva', models.FloatField()),
                ('total', models.FloatField()),
                ('idordenpaypal', models.CharField(max_length=255)),
                ('idestadoentrega', models.ForeignKey(db_column='idestadoentrega', on_delete=django.db.models.deletion.CASCADE, to='digital.confestadoentrega')),
                ('idusuariocompra', models.ForeignKey(db_column='idusuariocompra', on_delete=django.db.models.deletion.RESTRICT, related_name='ventas_comprador', to='digital.logusuarios')),
                ('idvendedor', models.ForeignKey(db_column='idvendedor', on_delete=django.db.models.deletion.RESTRICT, related_name='ventas_vendedor', to='digital.logusuarios')),
            ],
            options={
                'verbose_name_plural': 'Ventas Masetra',
                'db_table': 'ven_ventam',
                'ordering': ['id', 'fecha', 'hora', 'idusuariocompra', 'idvendedor', 'importe', 'descuento', 'iva', 'total', 'idestadoentrega', 'idordenpaypal'],
            },
        ),
        migrations.CreateModel(
            name='VentaDetalle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio', models.FloatField()),
                ('descuento', models.FloatField()),
                ('iva', models.FloatField()),
                ('total', models.FloatField()),
                ('idlibro', models.ForeignKey(db_column='idlibro', on_delete=django.db.models.deletion.RESTRICT, to='digital.catlibros')),
                ('idventa', models.ForeignKey(db_column='idventa', on_delete=django.db.models.deletion.RESTRICT, to='digital.venta')),
            ],
            options={
                'verbose_name_plural': 'Ventas Detalles',
                'db_table': 'ven_ventad',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Visualizacion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('idlibro', models.ForeignKey(db_column='idlibro', on_delete=django.db.models.deletion.RESTRICT, to='digital.catlibros')),
                ('idusuario', models.ForeignKey(db_column='idusuario', on_delete=django.db.models.deletion.RESTRICT, to='digital.logusuarios')),
            ],
            options={
                'verbose_name_plural': 'Visualizaciones',
                'db_table': 'inv_visualizaciones',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='confautor',
            index=models.Index(fields=['idnacionalidad'], name='conf_autore_idnacio_32ce4c_idx'),
        ),
    ]
